# Generated by Django 3.2.5 on 2021-08-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('por', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=64)),
                ('title', models.CharField(blank=True, default='', max_length=64)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('webLink', models.CharField(blank=True, default='', max_length=64)),
                ('imageLink', models.CharField(blank=True, default='', max_length=150)),
                ('imageOnHoverLink', models.CharField(blank=True, default='', max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='worksList',
            field=models.ManyToManyField(blank=True, related_name='users', to='por.Work'),
        ),
    ]
