# Generated by Django 3.2.5 on 2021-08-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('por', '0002_auto_20210822_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='whats',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
