# Generated by Django 3.2.5 on 2021-08-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('por', '0003_auto_20210822_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='FirstName',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='LastName',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
