# Generated by Django 3.2.5 on 2021-08-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('por', '0004_auto_20210822_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
